# Generated by Django 5.2.9 on 2026-01-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogsettings_color_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsettings',
            name='beian_code',
        ),
        migrations.RemoveField(
            model_name='blogsettings',
            name='gongan_beiancode',
        ),
        migrations.RemoveField(
            model_name='blogsettings',
            name='show_gongan_code',
        ),
    ]
