# Generated by Django 5.2.9 on 2026-01-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_alter_oauthuser_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthconfig',
            options={'ordering': ['-creation_time'], 'verbose_name': 'oauth config', 'verbose_name_plural': 'oauth config'},
        ),
    ]
